// Generated by tools/gen_gles.py from android.jar. Do not edit.
package javax.microedition.khronos.opengles;

public interface GL10Ext extends GL {
    int glQueryMatrixxOES(int[] p0, int p1, int[] p2, int p3);
    int glQueryMatrixxOES(java.nio.IntBuffer p0, java.nio.IntBuffer p1);
}
