// Generated by tools/gen_gles.py from android.jar. Do not edit.
package javax.microedition.khronos.opengles;

public interface GL11Ext extends GL {
    int GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES = 35742;
    int GL_MATRIX_INDEX_ARRAY_OES = 34884;
    int GL_MATRIX_INDEX_ARRAY_POINTER_OES = 34889;
    int GL_MATRIX_INDEX_ARRAY_SIZE_OES = 34886;
    int GL_MATRIX_INDEX_ARRAY_STRIDE_OES = 34888;
    int GL_MATRIX_INDEX_ARRAY_TYPE_OES = 34887;
    int GL_MATRIX_PALETTE_OES = 34880;
    int GL_MAX_PALETTE_MATRICES_OES = 34882;
    int GL_MAX_VERTEX_UNITS_OES = 34468;
    int GL_TEXTURE_CROP_RECT_OES = 35741;
    int GL_WEIGHT_ARRAY_BUFFER_BINDING_OES = 34974;
    int GL_WEIGHT_ARRAY_OES = 34477;
    int GL_WEIGHT_ARRAY_POINTER_OES = 34476;
    int GL_WEIGHT_ARRAY_SIZE_OES = 34475;
    int GL_WEIGHT_ARRAY_STRIDE_OES = 34474;
    int GL_WEIGHT_ARRAY_TYPE_OES = 34473;

    void glTexParameterfv(int p0, int p1, float[] p2, int p3);
    void glCurrentPaletteMatrixOES(int p0);
    void glDrawTexfOES(float p0, float p1, float p2, float p3, float p4);
    void glDrawTexfvOES(float[] p0, int p1);
    void glDrawTexfvOES(java.nio.FloatBuffer p0);
    void glDrawTexiOES(int p0, int p1, int p2, int p3, int p4);
    void glDrawTexivOES(int[] p0, int p1);
    void glDrawTexivOES(java.nio.IntBuffer p0);
    void glDrawTexsOES(short p0, short p1, short p2, short p3, short p4);
    void glDrawTexsvOES(short[] p0, int p1);
    void glDrawTexsvOES(java.nio.ShortBuffer p0);
    void glDrawTexxOES(int p0, int p1, int p2, int p3, int p4);
    void glDrawTexxvOES(int[] p0, int p1);
    void glDrawTexxvOES(java.nio.IntBuffer p0);
    void glEnable(int p0);
    void glEnableClientState(int p0);
    void glLoadPaletteFromModelViewMatrixOES();
    void glMatrixIndexPointerOES(int p0, int p1, int p2, java.nio.Buffer p3);
    void glMatrixIndexPointerOES(int p0, int p1, int p2, int p3);
    void glWeightPointerOES(int p0, int p1, int p2, java.nio.Buffer p3);
    void glWeightPointerOES(int p0, int p1, int p2, int p3);
}
