import java.io.*;
import java.lang.reflect.*;
import java.net.*;
import java.util.*;

/** Prints android/R.java (public resource ids) from an SDK android.jar. */
public class GenR {
    public static void main(String[] args) throws Exception {
        URLClassLoader cl = new URLClassLoader(new URL[] {new File(args[0]).toURI().toURL()}, null);
        Class<?> r = Class.forName("android.R", false, cl);
        StringBuilder sb = new StringBuilder();
        sb.append("/* Generated by tools/genr from the Android SDK: public framework resource ids. */\n");
        sb.append("package android;\n\npublic final class R {\n");
        Class<?>[] inner = r.getDeclaredClasses();
        Arrays.sort(inner, Comparator.comparing(Class::getSimpleName));
        for (Class<?> c : inner) {
            sb.append("    public static final class ").append(c.getSimpleName()).append(" {\n");
            Field[] fs = c.getDeclaredFields();
            Arrays.sort(fs, Comparator.comparing(Field::getName));
            for (Field f : fs) {
                int m = f.getModifiers();
                if (!Modifier.isStatic(m) || !Modifier.isPublic(m)) continue;
                if (f.getType() == int.class) {
                    sb.append("        public static final int ").append(f.getName()).append(" = 0x")
                      .append(String.format("%08x", f.getInt(null))).append(";\n");
                } else if (f.getType() == int[].class) {
                    int[] v = (int[]) f.get(null);
                    sb.append("        public static final int[] ").append(f.getName()).append(" = {");
                    for (int i = 0; i < v.length; i++) sb.append(i == 0 ? "" : ", ").append(String.format("0x%08x", v[i]));
                    sb.append("};\n");
                }
            }
            sb.append("    }\n");
        }
        sb.append("}\n");
        System.out.print(sb);
    }
}
