// Generated by tools/gen_gles.py from android.jar and the Khronos headers. Do not edit.
package android.opengl;


public class GLES10Ext {

    public GLES10Ext() {
    }

    public static native int glQueryMatrixxOES(int[] mantissa, int mantissaOffset, int[] exponent, int exponentOffset);
    public static native int glQueryMatrixxOES(java.nio.IntBuffer mantissa, java.nio.IntBuffer exponent);
}
