// Generated by tools/gen_gles.py from android.jar. Do not edit.
package com.google.android.gles_jni;

import javax.microedition.khronos.opengles.GL10;
import javax.microedition.khronos.opengles.GL10Ext;
import javax.microedition.khronos.opengles.GL11;
import javax.microedition.khronos.opengles.GL11Ext;
import javax.microedition.khronos.opengles.GL11ExtensionPack;

/** The GL object EGLContext.getGL() returns: forwards to the GLES10/GLES11 bindings. */
public class GLImpl implements GL10, GL10Ext, GL11, GL11Ext, GL11ExtensionPack {
    public GLImpl() {
    }

    public void glActiveTexture(int p0) {
        android.opengl.GLES10.glActiveTexture(p0);
    }

    public void glAlphaFunc(int p0, float p1) {
        android.opengl.GLES10.glAlphaFunc(p0, p1);
    }

    public void glAlphaFuncx(int p0, int p1) {
        android.opengl.GLES10.glAlphaFuncx(p0, p1);
    }

    public void glBindBuffer(int p0, int p1) {
        android.opengl.GLES11.glBindBuffer(p0, p1);
    }

    public void glBindFramebufferOES(int p0, int p1) {
        android.opengl.GLES11Ext.glBindFramebufferOES(p0, p1);
    }

    public void glBindRenderbufferOES(int p0, int p1) {
        android.opengl.GLES11Ext.glBindRenderbufferOES(p0, p1);
    }

    public void glBindTexture(int p0, int p1) {
        android.opengl.GLES10.glBindTexture(p0, p1);
    }

    public void glBlendEquation(int p0) {
        android.opengl.GLES20.glBlendEquation(p0);
    }

    public void glBlendEquationSeparate(int p0, int p1) {
        android.opengl.GLES20.glBlendEquationSeparate(p0, p1);
    }

    public void glBlendFunc(int p0, int p1) {
        android.opengl.GLES10.glBlendFunc(p0, p1);
    }

    public void glBlendFuncSeparate(int p0, int p1, int p2, int p3) {
        android.opengl.GLES20.glBlendFuncSeparate(p0, p1, p2, p3);
    }

    public void glBufferData(int p0, int p1, java.nio.Buffer p2, int p3) {
        android.opengl.GLES11.glBufferData(p0, p1, p2, p3);
    }

    public void glBufferSubData(int p0, int p1, int p2, java.nio.Buffer p3) {
        android.opengl.GLES11.glBufferSubData(p0, p1, p2, p3);
    }

    public int glCheckFramebufferStatusOES(int p0) {
        return android.opengl.GLES11Ext.glCheckFramebufferStatusOES(p0);
    }

    public void glClear(int p0) {
        android.opengl.GLES10.glClear(p0);
    }

    public void glClearColor(float p0, float p1, float p2, float p3) {
        android.opengl.GLES10.glClearColor(p0, p1, p2, p3);
    }

    public void glClearColorx(int p0, int p1, int p2, int p3) {
        android.opengl.GLES10.glClearColorx(p0, p1, p2, p3);
    }

    public void glClearDepthf(float p0) {
        android.opengl.GLES10.glClearDepthf(p0);
    }

    public void glClearDepthx(int p0) {
        android.opengl.GLES10.glClearDepthx(p0);
    }

    public void glClearStencil(int p0) {
        android.opengl.GLES10.glClearStencil(p0);
    }

    public void glClientActiveTexture(int p0) {
        android.opengl.GLES10.glClientActiveTexture(p0);
    }

    public void glClipPlanef(int p0, java.nio.FloatBuffer p1) {
        android.opengl.GLES11.glClipPlanef(p0, p1);
    }

    public void glClipPlanef(int p0, float[] p1, int p2) {
        android.opengl.GLES11.glClipPlanef(p0, p1, p2);
    }

    public void glClipPlanex(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES11.glClipPlanex(p0, p1);
    }

    public void glClipPlanex(int p0, int[] p1, int p2) {
        android.opengl.GLES11.glClipPlanex(p0, p1, p2);
    }

    public void glColor4f(float p0, float p1, float p2, float p3) {
        android.opengl.GLES10.glColor4f(p0, p1, p2, p3);
    }

    public void glColor4ub(byte p0, byte p1, byte p2, byte p3) {
        android.opengl.GLES11.glColor4ub(p0, p1, p2, p3);
    }

    public void glColor4x(int p0, int p1, int p2, int p3) {
        android.opengl.GLES10.glColor4x(p0, p1, p2, p3);
    }

    public void glColorMask(boolean p0, boolean p1, boolean p2, boolean p3) {
        android.opengl.GLES10.glColorMask(p0, p1, p2, p3);
    }

    public void glColorPointer(int p0, int p1, int p2, int p3) {
        android.opengl.GLES11.glColorPointer(p0, p1, p2, p3);
    }

    public void glColorPointer(int p0, int p1, int p2, java.nio.Buffer p3) {
        android.opengl.GLES10.glColorPointer(p0, p1, p2, p3);
    }

    public void glCompressedTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, java.nio.Buffer p7) {
        android.opengl.GLES10.glCompressedTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public void glCompressedTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.Buffer p8) {
        android.opengl.GLES10.glCompressedTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public void glCopyTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7) {
        android.opengl.GLES10.glCopyTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public void glCopyTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7) {
        android.opengl.GLES10.glCopyTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7);
    }

    public void glCullFace(int p0) {
        android.opengl.GLES10.glCullFace(p0);
    }

    public void glCurrentPaletteMatrixOES(int p0) {
        android.opengl.GLES11Ext.glCurrentPaletteMatrixOES(p0);
    }

    public void glDeleteBuffers(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES11.glDeleteBuffers(p0, p1);
    }

    public void glDeleteBuffers(int p0, int[] p1, int p2) {
        android.opengl.GLES11.glDeleteBuffers(p0, p1, p2);
    }

    public void glDeleteFramebuffersOES(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES11Ext.glDeleteFramebuffersOES(p0, p1);
    }

    public void glDeleteFramebuffersOES(int p0, int[] p1, int p2) {
        android.opengl.GLES11Ext.glDeleteFramebuffersOES(p0, p1, p2);
    }

    public void glDeleteRenderbuffersOES(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES11Ext.glDeleteRenderbuffersOES(p0, p1);
    }

    public void glDeleteRenderbuffersOES(int p0, int[] p1, int p2) {
        android.opengl.GLES11Ext.glDeleteRenderbuffersOES(p0, p1, p2);
    }

    public void glDeleteTextures(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES10.glDeleteTextures(p0, p1);
    }

    public void glDeleteTextures(int p0, int[] p1, int p2) {
        android.opengl.GLES10.glDeleteTextures(p0, p1, p2);
    }

    public void glDepthFunc(int p0) {
        android.opengl.GLES10.glDepthFunc(p0);
    }

    public void glDepthMask(boolean p0) {
        android.opengl.GLES10.glDepthMask(p0);
    }

    public void glDepthRangef(float p0, float p1) {
        android.opengl.GLES10.glDepthRangef(p0, p1);
    }

    public void glDepthRangex(int p0, int p1) {
        android.opengl.GLES10.glDepthRangex(p0, p1);
    }

    public void glDisable(int p0) {
        android.opengl.GLES10.glDisable(p0);
    }

    public void glDisableClientState(int p0) {
        android.opengl.GLES10.glDisableClientState(p0);
    }

    public void glDrawArrays(int p0, int p1, int p2) {
        android.opengl.GLES10.glDrawArrays(p0, p1, p2);
    }

    public void glDrawElements(int p0, int p1, int p2, int p3) {
        android.opengl.GLES11.glDrawElements(p0, p1, p2, p3);
    }

    public void glDrawElements(int p0, int p1, int p2, java.nio.Buffer p3) {
        android.opengl.GLES10.glDrawElements(p0, p1, p2, p3);
    }

    public void glDrawTexfOES(float p0, float p1, float p2, float p3, float p4) {
        android.opengl.GLES11Ext.glDrawTexfOES(p0, p1, p2, p3, p4);
    }

    public void glDrawTexfvOES(java.nio.FloatBuffer p0) {
        android.opengl.GLES11Ext.glDrawTexfvOES(p0);
    }

    public void glDrawTexfvOES(float[] p0, int p1) {
        android.opengl.GLES11Ext.glDrawTexfvOES(p0, p1);
    }

    public void glDrawTexiOES(int p0, int p1, int p2, int p3, int p4) {
        android.opengl.GLES11Ext.glDrawTexiOES(p0, p1, p2, p3, p4);
    }

    public void glDrawTexivOES(java.nio.IntBuffer p0) {
        android.opengl.GLES11Ext.glDrawTexivOES(p0);
    }

    public void glDrawTexivOES(int[] p0, int p1) {
        android.opengl.GLES11Ext.glDrawTexivOES(p0, p1);
    }

    public void glDrawTexsOES(short p0, short p1, short p2, short p3, short p4) {
        android.opengl.GLES11Ext.glDrawTexsOES(p0, p1, p2, p3, p4);
    }

    public void glDrawTexsvOES(java.nio.ShortBuffer p0) {
        android.opengl.GLES11Ext.glDrawTexsvOES(p0);
    }

    public void glDrawTexsvOES(short[] p0, int p1) {
        android.opengl.GLES11Ext.glDrawTexsvOES(p0, p1);
    }

    public void glDrawTexxOES(int p0, int p1, int p2, int p3, int p4) {
        android.opengl.GLES11Ext.glDrawTexxOES(p0, p1, p2, p3, p4);
    }

    public void glDrawTexxvOES(java.nio.IntBuffer p0) {
        android.opengl.GLES11Ext.glDrawTexxvOES(p0);
    }

    public void glDrawTexxvOES(int[] p0, int p1) {
        android.opengl.GLES11Ext.glDrawTexxvOES(p0, p1);
    }

    public void glEnable(int p0) {
        android.opengl.GLES10.glEnable(p0);
    }

    public void glEnableClientState(int p0) {
        android.opengl.GLES10.glEnableClientState(p0);
    }

    public void glFinish() {
        android.opengl.GLES10.glFinish();
    }

    public void glFlush() {
        android.opengl.GLES10.glFlush();
    }

    public void glFogf(int p0, float p1) {
        android.opengl.GLES10.glFogf(p0, p1);
    }

    public void glFogfv(int p0, java.nio.FloatBuffer p1) {
        android.opengl.GLES10.glFogfv(p0, p1);
    }

    public void glFogfv(int p0, float[] p1, int p2) {
        android.opengl.GLES10.glFogfv(p0, p1, p2);
    }

    public void glFogx(int p0, int p1) {
        android.opengl.GLES10.glFogx(p0, p1);
    }

    public void glFogxv(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES10.glFogxv(p0, p1);
    }

    public void glFogxv(int p0, int[] p1, int p2) {
        android.opengl.GLES10.glFogxv(p0, p1, p2);
    }

    public void glFramebufferRenderbufferOES(int p0, int p1, int p2, int p3) {
        android.opengl.GLES11Ext.glFramebufferRenderbufferOES(p0, p1, p2, p3);
    }

    public void glFramebufferTexture2DOES(int p0, int p1, int p2, int p3, int p4) {
        android.opengl.GLES11Ext.glFramebufferTexture2DOES(p0, p1, p2, p3, p4);
    }

    public void glFrontFace(int p0) {
        android.opengl.GLES10.glFrontFace(p0);
    }

    public void glFrustumf(float p0, float p1, float p2, float p3, float p4, float p5) {
        android.opengl.GLES10.glFrustumf(p0, p1, p2, p3, p4, p5);
    }

    public void glFrustumx(int p0, int p1, int p2, int p3, int p4, int p5) {
        android.opengl.GLES10.glFrustumx(p0, p1, p2, p3, p4, p5);
    }

    public void glGenBuffers(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES11.glGenBuffers(p0, p1);
    }

    public void glGenBuffers(int p0, int[] p1, int p2) {
        android.opengl.GLES11.glGenBuffers(p0, p1, p2);
    }

    public void glGenFramebuffersOES(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES11Ext.glGenFramebuffersOES(p0, p1);
    }

    public void glGenFramebuffersOES(int p0, int[] p1, int p2) {
        android.opengl.GLES11Ext.glGenFramebuffersOES(p0, p1, p2);
    }

    public void glGenRenderbuffersOES(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES11Ext.glGenRenderbuffersOES(p0, p1);
    }

    public void glGenRenderbuffersOES(int p0, int[] p1, int p2) {
        android.opengl.GLES11Ext.glGenRenderbuffersOES(p0, p1, p2);
    }

    public void glGenTextures(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES10.glGenTextures(p0, p1);
    }

    public void glGenTextures(int p0, int[] p1, int p2) {
        android.opengl.GLES10.glGenTextures(p0, p1, p2);
    }

    public void glGenerateMipmapOES(int p0) {
        android.opengl.GLES11Ext.glGenerateMipmapOES(p0);
    }

    public void glGetBooleanv(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES11.glGetBooleanv(p0, p1);
    }

    public void glGetBooleanv(int p0, boolean[] p1, int p2) {
        android.opengl.GLES11.glGetBooleanv(p0, p1, p2);
    }

    public void glGetBufferParameteriv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11.glGetBufferParameteriv(p0, p1, p2);
    }

    public void glGetBufferParameteriv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11.glGetBufferParameteriv(p0, p1, p2, p3);
    }

    public void glGetClipPlanef(int p0, java.nio.FloatBuffer p1) {
        android.opengl.GLES11.glGetClipPlanef(p0, p1);
    }

    public void glGetClipPlanef(int p0, float[] p1, int p2) {
        android.opengl.GLES11.glGetClipPlanef(p0, p1, p2);
    }

    public void glGetClipPlanex(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES11.glGetClipPlanex(p0, p1);
    }

    public void glGetClipPlanex(int p0, int[] p1, int p2) {
        android.opengl.GLES11.glGetClipPlanex(p0, p1, p2);
    }

    public int glGetError() {
        return android.opengl.GLES10.glGetError();
    }

    public void glGetFixedv(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES11.glGetFixedv(p0, p1);
    }

    public void glGetFixedv(int p0, int[] p1, int p2) {
        android.opengl.GLES11.glGetFixedv(p0, p1, p2);
    }

    public void glGetFloatv(int p0, java.nio.FloatBuffer p1) {
        android.opengl.GLES11.glGetFloatv(p0, p1);
    }

    public void glGetFloatv(int p0, float[] p1, int p2) {
        android.opengl.GLES11.glGetFloatv(p0, p1, p2);
    }

    public void glGetFramebufferAttachmentParameterivOES(int p0, int p1, int p2, java.nio.IntBuffer p3) {
        android.opengl.GLES11Ext.glGetFramebufferAttachmentParameterivOES(p0, p1, p2, p3);
    }

    public void glGetFramebufferAttachmentParameterivOES(int p0, int p1, int p2, int[] p3, int p4) {
        android.opengl.GLES11Ext.glGetFramebufferAttachmentParameterivOES(p0, p1, p2, p3, p4);
    }

    public void glGetIntegerv(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES10.glGetIntegerv(p0, p1);
    }

    public void glGetIntegerv(int p0, int[] p1, int p2) {
        android.opengl.GLES10.glGetIntegerv(p0, p1, p2);
    }

    public void glGetLightfv(int p0, int p1, java.nio.FloatBuffer p2) {
        android.opengl.GLES11.glGetLightfv(p0, p1, p2);
    }

    public void glGetLightfv(int p0, int p1, float[] p2, int p3) {
        android.opengl.GLES11.glGetLightfv(p0, p1, p2, p3);
    }

    public void glGetLightxv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11.glGetLightxv(p0, p1, p2);
    }

    public void glGetLightxv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11.glGetLightxv(p0, p1, p2, p3);
    }

    public void glGetMaterialfv(int p0, int p1, java.nio.FloatBuffer p2) {
        android.opengl.GLES11.glGetMaterialfv(p0, p1, p2);
    }

    public void glGetMaterialfv(int p0, int p1, float[] p2, int p3) {
        android.opengl.GLES11.glGetMaterialfv(p0, p1, p2, p3);
    }

    public void glGetMaterialxv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11.glGetMaterialxv(p0, p1, p2);
    }

    public void glGetMaterialxv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11.glGetMaterialxv(p0, p1, p2, p3);
    }

    public void glGetPointerv(int p0, java.nio.Buffer[] p1) {
        android.opengl.EGLNative.unsupported("GL.glGetPointerv");
    }

    public void glGetRenderbufferParameterivOES(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11Ext.glGetRenderbufferParameterivOES(p0, p1, p2);
    }

    public void glGetRenderbufferParameterivOES(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11Ext.glGetRenderbufferParameterivOES(p0, p1, p2, p3);
    }

    public String glGetString(int p0) {
        return android.opengl.GLES10.glGetString(p0);
    }

    public void glGetTexEnviv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11.glGetTexEnviv(p0, p1, p2);
    }

    public void glGetTexEnviv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11.glGetTexEnviv(p0, p1, p2, p3);
    }

    public void glGetTexEnvxv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11.glGetTexEnvxv(p0, p1, p2);
    }

    public void glGetTexEnvxv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11.glGetTexEnvxv(p0, p1, p2, p3);
    }

    public void glGetTexGenfv(int p0, int p1, java.nio.FloatBuffer p2) {
        android.opengl.GLES11Ext.glGetTexGenfvOES(p0, p1, p2);
    }

    public void glGetTexGenfv(int p0, int p1, float[] p2, int p3) {
        android.opengl.GLES11Ext.glGetTexGenfvOES(p0, p1, p2, p3);
    }

    public void glGetTexGeniv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11Ext.glGetTexGenivOES(p0, p1, p2);
    }

    public void glGetTexGeniv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11Ext.glGetTexGenivOES(p0, p1, p2, p3);
    }

    public void glGetTexGenxv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11Ext.glGetTexGenxvOES(p0, p1, p2);
    }

    public void glGetTexGenxv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11Ext.glGetTexGenxvOES(p0, p1, p2, p3);
    }

    public void glGetTexParameterfv(int p0, int p1, java.nio.FloatBuffer p2) {
        android.opengl.GLES11.glGetTexParameterfv(p0, p1, p2);
    }

    public void glGetTexParameterfv(int p0, int p1, float[] p2, int p3) {
        android.opengl.GLES11.glGetTexParameterfv(p0, p1, p2, p3);
    }

    public void glGetTexParameteriv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11.glGetTexParameteriv(p0, p1, p2);
    }

    public void glGetTexParameteriv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11.glGetTexParameteriv(p0, p1, p2, p3);
    }

    public void glGetTexParameterxv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11.glGetTexParameterxv(p0, p1, p2);
    }

    public void glGetTexParameterxv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11.glGetTexParameterxv(p0, p1, p2, p3);
    }

    public void glHint(int p0, int p1) {
        android.opengl.GLES10.glHint(p0, p1);
    }

    public boolean glIsBuffer(int p0) {
        return android.opengl.GLES11.glIsBuffer(p0);
    }

    public boolean glIsEnabled(int p0) {
        return android.opengl.GLES11.glIsEnabled(p0);
    }

    public boolean glIsFramebufferOES(int p0) {
        return android.opengl.GLES11Ext.glIsFramebufferOES(p0);
    }

    public boolean glIsRenderbufferOES(int p0) {
        return android.opengl.GLES11Ext.glIsRenderbufferOES(p0);
    }

    public boolean glIsTexture(int p0) {
        return android.opengl.GLES11.glIsTexture(p0);
    }

    public void glLightModelf(int p0, float p1) {
        android.opengl.GLES10.glLightModelf(p0, p1);
    }

    public void glLightModelfv(int p0, java.nio.FloatBuffer p1) {
        android.opengl.GLES10.glLightModelfv(p0, p1);
    }

    public void glLightModelfv(int p0, float[] p1, int p2) {
        android.opengl.GLES10.glLightModelfv(p0, p1, p2);
    }

    public void glLightModelx(int p0, int p1) {
        android.opengl.GLES10.glLightModelx(p0, p1);
    }

    public void glLightModelxv(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES10.glLightModelxv(p0, p1);
    }

    public void glLightModelxv(int p0, int[] p1, int p2) {
        android.opengl.GLES10.glLightModelxv(p0, p1, p2);
    }

    public void glLightf(int p0, int p1, float p2) {
        android.opengl.GLES10.glLightf(p0, p1, p2);
    }

    public void glLightfv(int p0, int p1, java.nio.FloatBuffer p2) {
        android.opengl.GLES10.glLightfv(p0, p1, p2);
    }

    public void glLightfv(int p0, int p1, float[] p2, int p3) {
        android.opengl.GLES10.glLightfv(p0, p1, p2, p3);
    }

    public void glLightx(int p0, int p1, int p2) {
        android.opengl.GLES10.glLightx(p0, p1, p2);
    }

    public void glLightxv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES10.glLightxv(p0, p1, p2);
    }

    public void glLightxv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES10.glLightxv(p0, p1, p2, p3);
    }

    public void glLineWidth(float p0) {
        android.opengl.GLES10.glLineWidth(p0);
    }

    public void glLineWidthx(int p0) {
        android.opengl.GLES10.glLineWidthx(p0);
    }

    public void glLoadIdentity() {
        android.opengl.GLES10.glLoadIdentity();
    }

    public void glLoadMatrixf(java.nio.FloatBuffer p0) {
        android.opengl.GLES10.glLoadMatrixf(p0);
    }

    public void glLoadMatrixf(float[] p0, int p1) {
        android.opengl.GLES10.glLoadMatrixf(p0, p1);
    }

    public void glLoadMatrixx(java.nio.IntBuffer p0) {
        android.opengl.GLES10.glLoadMatrixx(p0);
    }

    public void glLoadMatrixx(int[] p0, int p1) {
        android.opengl.GLES10.glLoadMatrixx(p0, p1);
    }

    public void glLoadPaletteFromModelViewMatrixOES() {
        android.opengl.GLES11Ext.glLoadPaletteFromModelViewMatrixOES();
    }

    public void glLogicOp(int p0) {
        android.opengl.GLES10.glLogicOp(p0);
    }

    public void glMaterialf(int p0, int p1, float p2) {
        android.opengl.GLES10.glMaterialf(p0, p1, p2);
    }

    public void glMaterialfv(int p0, int p1, java.nio.FloatBuffer p2) {
        android.opengl.GLES10.glMaterialfv(p0, p1, p2);
    }

    public void glMaterialfv(int p0, int p1, float[] p2, int p3) {
        android.opengl.GLES10.glMaterialfv(p0, p1, p2, p3);
    }

    public void glMaterialx(int p0, int p1, int p2) {
        android.opengl.GLES10.glMaterialx(p0, p1, p2);
    }

    public void glMaterialxv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES10.glMaterialxv(p0, p1, p2);
    }

    public void glMaterialxv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES10.glMaterialxv(p0, p1, p2, p3);
    }

    public void glMatrixIndexPointerOES(int p0, int p1, int p2, int p3) {
        android.opengl.EGLNative.unsupported("GL.glMatrixIndexPointerOES");
    }

    public void glMatrixIndexPointerOES(int p0, int p1, int p2, java.nio.Buffer p3) {
        android.opengl.GLES11Ext.glMatrixIndexPointerOES(p0, p1, p2, p3);
    }

    public void glMatrixMode(int p0) {
        android.opengl.GLES10.glMatrixMode(p0);
    }

    public void glMultMatrixf(java.nio.FloatBuffer p0) {
        android.opengl.GLES10.glMultMatrixf(p0);
    }

    public void glMultMatrixf(float[] p0, int p1) {
        android.opengl.GLES10.glMultMatrixf(p0, p1);
    }

    public void glMultMatrixx(java.nio.IntBuffer p0) {
        android.opengl.GLES10.glMultMatrixx(p0);
    }

    public void glMultMatrixx(int[] p0, int p1) {
        android.opengl.GLES10.glMultMatrixx(p0, p1);
    }

    public void glMultiTexCoord4f(int p0, float p1, float p2, float p3, float p4) {
        android.opengl.GLES10.glMultiTexCoord4f(p0, p1, p2, p3, p4);
    }

    public void glMultiTexCoord4x(int p0, int p1, int p2, int p3, int p4) {
        android.opengl.GLES10.glMultiTexCoord4x(p0, p1, p2, p3, p4);
    }

    public void glNormal3f(float p0, float p1, float p2) {
        android.opengl.GLES10.glNormal3f(p0, p1, p2);
    }

    public void glNormal3x(int p0, int p1, int p2) {
        android.opengl.GLES10.glNormal3x(p0, p1, p2);
    }

    public void glNormalPointer(int p0, int p1, int p2) {
        android.opengl.GLES11.glNormalPointer(p0, p1, p2);
    }

    public void glNormalPointer(int p0, int p1, java.nio.Buffer p2) {
        android.opengl.GLES10.glNormalPointer(p0, p1, p2);
    }

    public void glOrthof(float p0, float p1, float p2, float p3, float p4, float p5) {
        android.opengl.GLES10.glOrthof(p0, p1, p2, p3, p4, p5);
    }

    public void glOrthox(int p0, int p1, int p2, int p3, int p4, int p5) {
        android.opengl.GLES10.glOrthox(p0, p1, p2, p3, p4, p5);
    }

    public void glPixelStorei(int p0, int p1) {
        android.opengl.GLES10.glPixelStorei(p0, p1);
    }

    public void glPointParameterf(int p0, float p1) {
        android.opengl.GLES11.glPointParameterf(p0, p1);
    }

    public void glPointParameterfv(int p0, java.nio.FloatBuffer p1) {
        android.opengl.GLES11.glPointParameterfv(p0, p1);
    }

    public void glPointParameterfv(int p0, float[] p1, int p2) {
        android.opengl.GLES11.glPointParameterfv(p0, p1, p2);
    }

    public void glPointParameterx(int p0, int p1) {
        android.opengl.GLES11.glPointParameterx(p0, p1);
    }

    public void glPointParameterxv(int p0, java.nio.IntBuffer p1) {
        android.opengl.GLES11.glPointParameterxv(p0, p1);
    }

    public void glPointParameterxv(int p0, int[] p1, int p2) {
        android.opengl.GLES11.glPointParameterxv(p0, p1, p2);
    }

    public void glPointSize(float p0) {
        android.opengl.GLES10.glPointSize(p0);
    }

    public void glPointSizePointerOES(int p0, int p1, java.nio.Buffer p2) {
        android.opengl.GLES11.glPointSizePointerOES(p0, p1, p2);
    }

    public void glPointSizex(int p0) {
        android.opengl.GLES10.glPointSizex(p0);
    }

    public void glPolygonOffset(float p0, float p1) {
        android.opengl.GLES10.glPolygonOffset(p0, p1);
    }

    public void glPolygonOffsetx(int p0, int p1) {
        android.opengl.GLES10.glPolygonOffsetx(p0, p1);
    }

    public void glPopMatrix() {
        android.opengl.GLES10.glPopMatrix();
    }

    public void glPushMatrix() {
        android.opengl.GLES10.glPushMatrix();
    }

    public int glQueryMatrixxOES(java.nio.IntBuffer p0, java.nio.IntBuffer p1) {
        return android.opengl.GLES10Ext.glQueryMatrixxOES(p0, p1);
    }

    public int glQueryMatrixxOES(int[] p0, int p1, int[] p2, int p3) {
        return android.opengl.GLES10Ext.glQueryMatrixxOES(p0, p1, p2, p3);
    }

    public void glReadPixels(int p0, int p1, int p2, int p3, int p4, int p5, java.nio.Buffer p6) {
        android.opengl.GLES10.glReadPixels(p0, p1, p2, p3, p4, p5, p6);
    }

    public void glRenderbufferStorageOES(int p0, int p1, int p2, int p3) {
        android.opengl.GLES11Ext.glRenderbufferStorageOES(p0, p1, p2, p3);
    }

    public void glRotatef(float p0, float p1, float p2, float p3) {
        android.opengl.GLES10.glRotatef(p0, p1, p2, p3);
    }

    public void glRotatex(int p0, int p1, int p2, int p3) {
        android.opengl.GLES10.glRotatex(p0, p1, p2, p3);
    }

    public void glSampleCoverage(float p0, boolean p1) {
        android.opengl.GLES10.glSampleCoverage(p0, p1);
    }

    public void glSampleCoveragex(int p0, boolean p1) {
        android.opengl.GLES10.glSampleCoveragex(p0, p1);
    }

    public void glScalef(float p0, float p1, float p2) {
        android.opengl.GLES10.glScalef(p0, p1, p2);
    }

    public void glScalex(int p0, int p1, int p2) {
        android.opengl.GLES10.glScalex(p0, p1, p2);
    }

    public void glScissor(int p0, int p1, int p2, int p3) {
        android.opengl.GLES10.glScissor(p0, p1, p2, p3);
    }

    public void glShadeModel(int p0) {
        android.opengl.GLES10.glShadeModel(p0);
    }

    public void glStencilFunc(int p0, int p1, int p2) {
        android.opengl.GLES10.glStencilFunc(p0, p1, p2);
    }

    public void glStencilMask(int p0) {
        android.opengl.GLES10.glStencilMask(p0);
    }

    public void glStencilOp(int p0, int p1, int p2) {
        android.opengl.GLES10.glStencilOp(p0, p1, p2);
    }

    public void glTexCoordPointer(int p0, int p1, int p2, int p3) {
        android.opengl.GLES11.glTexCoordPointer(p0, p1, p2, p3);
    }

    public void glTexCoordPointer(int p0, int p1, int p2, java.nio.Buffer p3) {
        android.opengl.GLES10.glTexCoordPointer(p0, p1, p2, p3);
    }

    public void glTexEnvf(int p0, int p1, float p2) {
        android.opengl.GLES10.glTexEnvf(p0, p1, p2);
    }

    public void glTexEnvfv(int p0, int p1, java.nio.FloatBuffer p2) {
        android.opengl.GLES10.glTexEnvfv(p0, p1, p2);
    }

    public void glTexEnvfv(int p0, int p1, float[] p2, int p3) {
        android.opengl.GLES10.glTexEnvfv(p0, p1, p2, p3);
    }

    public void glTexEnvi(int p0, int p1, int p2) {
        android.opengl.GLES11.glTexEnvi(p0, p1, p2);
    }

    public void glTexEnviv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11.glTexEnviv(p0, p1, p2);
    }

    public void glTexEnviv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11.glTexEnviv(p0, p1, p2, p3);
    }

    public void glTexEnvx(int p0, int p1, int p2) {
        android.opengl.GLES10.glTexEnvx(p0, p1, p2);
    }

    public void glTexEnvxv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES10.glTexEnvxv(p0, p1, p2);
    }

    public void glTexEnvxv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES10.glTexEnvxv(p0, p1, p2, p3);
    }

    public void glTexGenf(int p0, int p1, float p2) {
        android.opengl.GLES11Ext.glTexGenfOES(p0, p1, p2);
    }

    public void glTexGenfv(int p0, int p1, java.nio.FloatBuffer p2) {
        android.opengl.GLES11Ext.glTexGenfvOES(p0, p1, p2);
    }

    public void glTexGenfv(int p0, int p1, float[] p2, int p3) {
        android.opengl.GLES11Ext.glTexGenfvOES(p0, p1, p2, p3);
    }

    public void glTexGeni(int p0, int p1, int p2) {
        android.opengl.GLES11Ext.glTexGeniOES(p0, p1, p2);
    }

    public void glTexGeniv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11Ext.glTexGenivOES(p0, p1, p2);
    }

    public void glTexGeniv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11Ext.glTexGenivOES(p0, p1, p2, p3);
    }

    public void glTexGenx(int p0, int p1, int p2) {
        android.opengl.GLES11Ext.glTexGenxOES(p0, p1, p2);
    }

    public void glTexGenxv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11Ext.glTexGenxvOES(p0, p1, p2);
    }

    public void glTexGenxv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11Ext.glTexGenxvOES(p0, p1, p2, p3);
    }

    public void glTexImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.Buffer p8) {
        android.opengl.GLES10.glTexImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public void glTexParameterf(int p0, int p1, float p2) {
        android.opengl.GLES10.glTexParameterf(p0, p1, p2);
    }

    public void glTexParameterfv(int p0, int p1, java.nio.FloatBuffer p2) {
        android.opengl.GLES11.glTexParameterfv(p0, p1, p2);
    }

    public void glTexParameterfv(int p0, int p1, float[] p2, int p3) {
        android.opengl.GLES11.glTexParameterfv(p0, p1, p2, p3);
    }

    public void glTexParameteri(int p0, int p1, int p2) {
        android.opengl.GLES11.glTexParameteri(p0, p1, p2);
    }

    public void glTexParameteriv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11.glTexParameteriv(p0, p1, p2);
    }

    public void glTexParameteriv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11.glTexParameteriv(p0, p1, p2, p3);
    }

    public void glTexParameterx(int p0, int p1, int p2) {
        android.opengl.GLES10.glTexParameterx(p0, p1, p2);
    }

    public void glTexParameterxv(int p0, int p1, java.nio.IntBuffer p2) {
        android.opengl.GLES11.glTexParameterxv(p0, p1, p2);
    }

    public void glTexParameterxv(int p0, int p1, int[] p2, int p3) {
        android.opengl.GLES11.glTexParameterxv(p0, p1, p2, p3);
    }

    public void glTexSubImage2D(int p0, int p1, int p2, int p3, int p4, int p5, int p6, int p7, java.nio.Buffer p8) {
        android.opengl.GLES10.glTexSubImage2D(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    public void glTranslatef(float p0, float p1, float p2) {
        android.opengl.GLES10.glTranslatef(p0, p1, p2);
    }

    public void glTranslatex(int p0, int p1, int p2) {
        android.opengl.GLES10.glTranslatex(p0, p1, p2);
    }

    public void glVertexPointer(int p0, int p1, int p2, int p3) {
        android.opengl.GLES11.glVertexPointer(p0, p1, p2, p3);
    }

    public void glVertexPointer(int p0, int p1, int p2, java.nio.Buffer p3) {
        android.opengl.GLES10.glVertexPointer(p0, p1, p2, p3);
    }

    public void glViewport(int p0, int p1, int p2, int p3) {
        android.opengl.GLES10.glViewport(p0, p1, p2, p3);
    }

    public void glWeightPointerOES(int p0, int p1, int p2, int p3) {
        android.opengl.EGLNative.unsupported("GL.glWeightPointerOES");
    }

    public void glWeightPointerOES(int p0, int p1, int p2, java.nio.Buffer p3) {
        android.opengl.GLES11Ext.glWeightPointerOES(p0, p1, p2, p3);
    }

}
