/* Generated by tools/gen_gles.py from the Khronos headers. Do not edit. */
/* X(return type, name, (parameter list)) for every GL ES entry point the bindings use. */
#define SA_GL_FUNCS(X) \
    X(void, glActiveShaderProgram, (uint32_t pipeline, uint32_t program)) \
    X(void, glActiveTexture, (uint32_t texture)) \
    X(void, glAlphaFunc, (uint32_t func, float ref)) \
    X(void, glAlphaFuncx, (uint32_t func, int32_t ref)) \
    X(void, glAlphaFuncxOES, (uint32_t func, int32_t ref)) \
    X(void, glAttachShader, (uint32_t program, uint32_t shader)) \
    X(void, glBeginQuery, (uint32_t target, uint32_t id)) \
    X(void, glBeginTransformFeedback, (uint32_t primitiveMode)) \
    X(void, glBindAttribLocation, (uint32_t program, uint32_t index, const void *name)) \
    X(void, glBindBuffer, (uint32_t target, uint32_t buffer)) \
    X(void, glBindBufferBase, (uint32_t target, uint32_t index, uint32_t buffer)) \
    X(void, glBindBufferRange, (uint32_t target, uint32_t index, uint32_t buffer, intptr_t offset, intptr_t size)) \
    X(void, glBindFramebuffer, (uint32_t target, uint32_t framebuffer)) \
    X(void, glBindFramebufferOES, (uint32_t target, uint32_t framebuffer)) \
    X(void, glBindImageTexture, (uint32_t unit, uint32_t texture, int32_t level, uint8_t layered, int32_t layer, uint32_t access, uint32_t format)) \
    X(void, glBindProgramPipeline, (uint32_t pipeline)) \
    X(void, glBindRenderbuffer, (uint32_t target, uint32_t renderbuffer)) \
    X(void, glBindRenderbufferOES, (uint32_t target, uint32_t renderbuffer)) \
    X(void, glBindSampler, (uint32_t unit, uint32_t sampler)) \
    X(void, glBindTexture, (uint32_t target, uint32_t texture)) \
    X(void, glBindTransformFeedback, (uint32_t target, uint32_t id)) \
    X(void, glBindVertexArray, (uint32_t array)) \
    X(void, glBindVertexBuffer, (uint32_t bindingindex, uint32_t buffer, intptr_t offset, int32_t stride)) \
    X(void, glBlendBarrier, (void)) \
    X(void, glBlendBarrierKHR, (void)) \
    X(void, glBlendColor, (float red, float green, float blue, float alpha)) \
    X(void, glBlendEquation, (uint32_t mode)) \
    X(void, glBlendEquationOES, (uint32_t mode)) \
    X(void, glBlendEquationSeparate, (uint32_t modeRGB, uint32_t modeAlpha)) \
    X(void, glBlendEquationSeparateOES, (uint32_t modeRGB, uint32_t modeAlpha)) \
    X(void, glBlendEquationSeparatei, (uint32_t buf, uint32_t modeRGB, uint32_t modeAlpha)) \
    X(void, glBlendEquationSeparateiEXT, (uint32_t buf, uint32_t modeRGB, uint32_t modeAlpha)) \
    X(void, glBlendEquationi, (uint32_t buf, uint32_t mode)) \
    X(void, glBlendEquationiEXT, (uint32_t buf, uint32_t mode)) \
    X(void, glBlendFunc, (uint32_t sfactor, uint32_t dfactor)) \
    X(void, glBlendFuncSeparate, (uint32_t sfactorRGB, uint32_t dfactorRGB, uint32_t sfactorAlpha, uint32_t dfactorAlpha)) \
    X(void, glBlendFuncSeparateOES, (uint32_t srcRGB, uint32_t dstRGB, uint32_t srcAlpha, uint32_t dstAlpha)) \
    X(void, glBlendFuncSeparatei, (uint32_t buf, uint32_t srcRGB, uint32_t dstRGB, uint32_t srcAlpha, uint32_t dstAlpha)) \
    X(void, glBlendFuncSeparateiEXT, (uint32_t buf, uint32_t srcRGB, uint32_t dstRGB, uint32_t srcAlpha, uint32_t dstAlpha)) \
    X(void, glBlendFunci, (uint32_t buf, uint32_t src, uint32_t dst)) \
    X(void, glBlendFunciEXT, (uint32_t buf, uint32_t src, uint32_t dst)) \
    X(void, glBlitFramebuffer, (int32_t srcX0, int32_t srcY0, int32_t srcX1, int32_t srcY1, int32_t dstX0, int32_t dstY0, int32_t dstX1, int32_t dstY1, uint32_t mask, uint32_t filter)) \
    X(void, glBufferData, (uint32_t target, intptr_t size, const void *data, uint32_t usage)) \
    X(void, glBufferSubData, (uint32_t target, intptr_t offset, intptr_t size, const void *data)) \
    X(uint32_t, glCheckFramebufferStatus, (uint32_t target)) \
    X(uint32_t, glCheckFramebufferStatusOES, (uint32_t target)) \
    X(void, glClear, (uint32_t mask)) \
    X(void, glClearBufferfi, (uint32_t buffer, int32_t drawbuffer, float depth, int32_t stencil)) \
    X(void, glClearBufferfv, (uint32_t buffer, int32_t drawbuffer, const void *value)) \
    X(void, glClearBufferiv, (uint32_t buffer, int32_t drawbuffer, const void *value)) \
    X(void, glClearBufferuiv, (uint32_t buffer, int32_t drawbuffer, const void *value)) \
    X(void, glClearColor, (float red, float green, float blue, float alpha)) \
    X(void, glClearColorx, (int32_t red, int32_t green, int32_t blue, int32_t alpha)) \
    X(void, glClearColorxOES, (int32_t red, int32_t green, int32_t blue, int32_t alpha)) \
    X(void, glClearDepthf, (float d)) \
    X(void, glClearDepthfOES, (float depth)) \
    X(void, glClearDepthx, (int32_t depth)) \
    X(void, glClearDepthxOES, (int32_t depth)) \
    X(void, glClearStencil, (int32_t s)) \
    X(void, glClientActiveTexture, (uint32_t texture)) \
    X(uint32_t, glClientWaitSync, (void *sync, uint32_t flags, uint64_t timeout)) \
    X(void, glClipPlanef, (uint32_t p, const void *eqn)) \
    X(void, glClipPlanefOES, (uint32_t plane, const void *equation)) \
    X(void, glClipPlanex, (uint32_t plane, const void *equation)) \
    X(void, glClipPlanexOES, (uint32_t plane, const void *equation)) \
    X(void, glColor4f, (float red, float green, float blue, float alpha)) \
    X(void, glColor4ub, (uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha)) \
    X(void, glColor4x, (int32_t red, int32_t green, int32_t blue, int32_t alpha)) \
    X(void, glColor4xOES, (int32_t red, int32_t green, int32_t blue, int32_t alpha)) \
    X(void, glColorMask, (uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha)) \
    X(void, glColorMaski, (uint32_t index, uint8_t r, uint8_t g, uint8_t b, uint8_t a)) \
    X(void, glColorMaskiEXT, (uint32_t index, uint8_t r, uint8_t g, uint8_t b, uint8_t a)) \
    X(void, glColorPointer, (int32_t size, uint32_t type, int32_t stride, const void *pointer)) \
    X(void, glCompileShader, (uint32_t shader)) \
    X(void, glCompressedTexImage2D, (uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t border, int32_t imageSize, const void *data)) \
    X(void, glCompressedTexImage3D, (uint32_t target, int32_t level, uint32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, int32_t imageSize, const void *data)) \
    X(void, glCompressedTexSubImage2D, (uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, int32_t imageSize, const void *data)) \
    X(void, glCompressedTexSubImage3D, (uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, int32_t imageSize, const void *data)) \
    X(void, glCopyBufferSubData, (uint32_t readTarget, uint32_t writeTarget, intptr_t readOffset, intptr_t writeOffset, intptr_t size)) \
    X(void, glCopyImageSubData, (uint32_t srcName, uint32_t srcTarget, int32_t srcLevel, int32_t srcX, int32_t srcY, int32_t srcZ, uint32_t dstName, uint32_t dstTarget, int32_t dstLevel, int32_t dstX, int32_t dstY, int32_t dstZ, int32_t srcWidth, int32_t srcHeight, int32_t srcDepth)) \
    X(void, glCopyImageSubDataEXT, (uint32_t srcName, uint32_t srcTarget, int32_t srcLevel, int32_t srcX, int32_t srcY, int32_t srcZ, uint32_t dstName, uint32_t dstTarget, int32_t dstLevel, int32_t dstX, int32_t dstY, int32_t dstZ, int32_t srcWidth, int32_t srcHeight, int32_t srcDepth)) \
    X(void, glCopyTexImage2D, (uint32_t target, int32_t level, uint32_t internalformat, int32_t x, int32_t y, int32_t width, int32_t height, int32_t border)) \
    X(void, glCopyTexSubImage2D, (uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t x, int32_t y, int32_t width, int32_t height)) \
    X(void, glCopyTexSubImage3D, (uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t x, int32_t y, int32_t width, int32_t height)) \
    X(uint32_t, glCreateProgram, (void)) \
    X(uint32_t, glCreateShader, (uint32_t type)) \
    X(uint32_t, glCreateShaderProgramv, (uint32_t type, int32_t count, const char *const *strings)) \
    X(void, glCullFace, (uint32_t mode)) \
    X(void, glCurrentPaletteMatrixOES, (uint32_t matrixpaletteindex)) \
    X(void, glDebugMessageCallback, (void *callback, const void *userParam)) \
    X(void, glDebugMessageCallbackKHR, (void *callback, const void *userParam)) \
    X(void, glDebugMessageControl, (uint32_t source, uint32_t type, uint32_t severity, int32_t count, const void *ids, uint8_t enabled)) \
    X(void, glDebugMessageControlKHR, (uint32_t source, uint32_t type, uint32_t severity, int32_t count, const void *ids, uint8_t enabled)) \
    X(void, glDebugMessageInsert, (uint32_t source, uint32_t type, uint32_t id, uint32_t severity, int32_t length, const void *buf)) \
    X(void, glDeleteBuffers, (int32_t n, const void *buffers)) \
    X(void, glDeleteFramebuffers, (int32_t n, const void *framebuffers)) \
    X(void, glDeleteFramebuffersOES, (int32_t n, const void *framebuffers)) \
    X(void, glDeleteProgram, (uint32_t program)) \
    X(void, glDeleteProgramPipelines, (int32_t n, const void *pipelines)) \
    X(void, glDeleteQueries, (int32_t n, const void *ids)) \
    X(void, glDeleteRenderbuffers, (int32_t n, const void *renderbuffers)) \
    X(void, glDeleteRenderbuffersOES, (int32_t n, const void *renderbuffers)) \
    X(void, glDeleteSamplers, (int32_t count, const void *samplers)) \
    X(void, glDeleteShader, (uint32_t shader)) \
    X(void, glDeleteSync, (void *sync)) \
    X(void, glDeleteTextures, (int32_t n, const void *textures)) \
    X(void, glDeleteTransformFeedbacks, (int32_t n, const void *ids)) \
    X(void, glDeleteVertexArrays, (int32_t n, const void *arrays)) \
    X(void, glDepthFunc, (uint32_t func)) \
    X(void, glDepthMask, (uint8_t flag)) \
    X(void, glDepthRangef, (float n, float f)) \
    X(void, glDepthRangefOES, (float n, float f)) \
    X(void, glDepthRangex, (int32_t n, int32_t f)) \
    X(void, glDepthRangexOES, (int32_t n, int32_t f)) \
    X(void, glDetachShader, (uint32_t program, uint32_t shader)) \
    X(void, glDisable, (uint32_t cap)) \
    X(void, glDisableClientState, (uint32_t array)) \
    X(void, glDisableVertexAttribArray, (uint32_t index)) \
    X(void, glDisablei, (uint32_t target, uint32_t index)) \
    X(void, glDisableiEXT, (uint32_t target, uint32_t index)) \
    X(void, glDispatchCompute, (uint32_t num_groups_x, uint32_t num_groups_y, uint32_t num_groups_z)) \
    X(void, glDispatchComputeIndirect, (intptr_t indirect)) \
    X(void, glDrawArrays, (uint32_t mode, int32_t first, int32_t count)) \
    X(void, glDrawArraysIndirect, (uint32_t mode, const void *indirect)) \
    X(void, glDrawArraysInstanced, (uint32_t mode, int32_t first, int32_t count, int32_t instancecount)) \
    X(void, glDrawBuffers, (int32_t n, const void *bufs)) \
    X(void, glDrawElements, (uint32_t mode, int32_t count, uint32_t type, const void *indices)) \
    X(void, glDrawElementsBaseVertex, (uint32_t mode, int32_t count, uint32_t type, const void *indices, int32_t basevertex)) \
    X(void, glDrawElementsIndirect, (uint32_t mode, uint32_t type, const void *indirect)) \
    X(void, glDrawElementsInstanced, (uint32_t mode, int32_t count, uint32_t type, const void *indices, int32_t instancecount)) \
    X(void, glDrawElementsInstancedBaseVertex, (uint32_t mode, int32_t count, uint32_t type, const void *indices, int32_t instancecount, int32_t basevertex)) \
    X(void, glDrawRangeElements, (uint32_t mode, uint32_t start, uint32_t end, int32_t count, uint32_t type, const void *indices)) \
    X(void, glDrawRangeElementsBaseVertex, (uint32_t mode, uint32_t start, uint32_t end, int32_t count, uint32_t type, const void *indices, int32_t basevertex)) \
    X(void, glDrawTexfOES, (float x, float y, float z, float width, float height)) \
    X(void, glDrawTexfvOES, (const void *coords)) \
    X(void, glDrawTexiOES, (int32_t x, int32_t y, int32_t z, int32_t width, int32_t height)) \
    X(void, glDrawTexivOES, (const void *coords)) \
    X(void, glDrawTexsOES, (int16_t x, int16_t y, int16_t z, int16_t width, int16_t height)) \
    X(void, glDrawTexsvOES, (const void *coords)) \
    X(void, glDrawTexxOES, (int32_t x, int32_t y, int32_t z, int32_t width, int32_t height)) \
    X(void, glDrawTexxvOES, (const void *coords)) \
    X(void, glEGLImageTargetRenderbufferStorageOES, (uint32_t target, void *image)) \
    X(void, glEGLImageTargetTexture2DOES, (uint32_t target, void *image)) \
    X(void, glEnable, (uint32_t cap)) \
    X(void, glEnableClientState, (uint32_t array)) \
    X(void, glEnableVertexAttribArray, (uint32_t index)) \
    X(void, glEnablei, (uint32_t target, uint32_t index)) \
    X(void, glEnableiEXT, (uint32_t target, uint32_t index)) \
    X(void, glEndQuery, (uint32_t target)) \
    X(void, glEndTransformFeedback, (void)) \
    X(void *, glFenceSync, (uint32_t condition, uint32_t flags)) \
    X(void, glFinish, (void)) \
    X(void, glFlush, (void)) \
    X(void, glFlushMappedBufferRange, (uint32_t target, intptr_t offset, intptr_t length)) \
    X(void, glFogf, (uint32_t pname, float param)) \
    X(void, glFogfv, (uint32_t pname, const void *params)) \
    X(void, glFogx, (uint32_t pname, int32_t param)) \
    X(void, glFogxOES, (uint32_t pname, int32_t param)) \
    X(void, glFogxv, (uint32_t pname, const void *param)) \
    X(void, glFogxvOES, (uint32_t pname, const void *param)) \
    X(void, glFramebufferParameteri, (uint32_t target, uint32_t pname, int32_t param)) \
    X(void, glFramebufferRenderbuffer, (uint32_t target, uint32_t attachment, uint32_t renderbuffertarget, uint32_t renderbuffer)) \
    X(void, glFramebufferRenderbufferOES, (uint32_t target, uint32_t attachment, uint32_t renderbuffertarget, uint32_t renderbuffer)) \
    X(void, glFramebufferTexture, (uint32_t target, uint32_t attachment, uint32_t texture, int32_t level)) \
    X(void, glFramebufferTexture2D, (uint32_t target, uint32_t attachment, uint32_t textarget, uint32_t texture, int32_t level)) \
    X(void, glFramebufferTexture2DOES, (uint32_t target, uint32_t attachment, uint32_t textarget, uint32_t texture, int32_t level)) \
    X(void, glFramebufferTextureEXT, (uint32_t target, uint32_t attachment, uint32_t texture, int32_t level)) \
    X(void, glFramebufferTextureLayer, (uint32_t target, uint32_t attachment, uint32_t texture, int32_t level, int32_t layer)) \
    X(void, glFrontFace, (uint32_t mode)) \
    X(void, glFrustumf, (float l, float r, float b, float t, float n, float f)) \
    X(void, glFrustumfOES, (float l, float r, float b, float t, float n, float f)) \
    X(void, glFrustumx, (int32_t l, int32_t r, int32_t b, int32_t t, int32_t n, int32_t f)) \
    X(void, glFrustumxOES, (int32_t l, int32_t r, int32_t b, int32_t t, int32_t n, int32_t f)) \
    X(void, glGenBuffers, (int32_t n, void *buffers)) \
    X(void, glGenFramebuffers, (int32_t n, void *framebuffers)) \
    X(void, glGenFramebuffersOES, (int32_t n, void *framebuffers)) \
    X(void, glGenProgramPipelines, (int32_t n, void *pipelines)) \
    X(void, glGenQueries, (int32_t n, void *ids)) \
    X(void, glGenRenderbuffers, (int32_t n, void *renderbuffers)) \
    X(void, glGenRenderbuffersOES, (int32_t n, void *renderbuffers)) \
    X(void, glGenSamplers, (int32_t count, void *samplers)) \
    X(void, glGenTextures, (int32_t n, void *textures)) \
    X(void, glGenTransformFeedbacks, (int32_t n, void *ids)) \
    X(void, glGenVertexArrays, (int32_t n, void *arrays)) \
    X(void, glGenerateMipmap, (uint32_t target)) \
    X(void, glGenerateMipmapOES, (uint32_t target)) \
    X(void, glGetActiveAttrib, (uint32_t program, uint32_t index, int32_t bufSize, void *length, void *size, void *type, void *name)) \
    X(void, glGetActiveUniform, (uint32_t program, uint32_t index, int32_t bufSize, void *length, void *size, void *type, void *name)) \
    X(void, glGetActiveUniformBlockName, (uint32_t program, uint32_t uniformBlockIndex, int32_t bufSize, void *length, void *uniformBlockName)) \
    X(void, glGetActiveUniformBlockiv, (uint32_t program, uint32_t uniformBlockIndex, uint32_t pname, void *params)) \
    X(void, glGetActiveUniformsiv, (uint32_t program, int32_t uniformCount, const void *uniformIndices, uint32_t pname, void *params)) \
    X(void, glGetAttachedShaders, (uint32_t program, int32_t maxCount, void *count, void *shaders)) \
    X(int32_t, glGetAttribLocation, (uint32_t program, const void *name)) \
    X(void, glGetBooleani_v, (uint32_t target, uint32_t index, void *data)) \
    X(void, glGetBooleanv, (uint32_t pname, void *data)) \
    X(void, glGetBufferParameteri64v, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetBufferParameteriv, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetBufferPointerv, (uint32_t target, uint32_t pname, void **params)) \
    X(void, glGetClipPlanef, (uint32_t plane, void *equation)) \
    X(void, glGetClipPlanefOES, (uint32_t plane, void *equation)) \
    X(void, glGetClipPlanex, (uint32_t plane, void *equation)) \
    X(void, glGetClipPlanexOES, (uint32_t plane, void *equation)) \
    X(uint32_t, glGetDebugMessageLog, (uint32_t count, int32_t bufSize, void *sources, void *types, void *ids, void *severities, void *lengths, void *messageLog)) \
    X(uint32_t, glGetDebugMessageLogKHR, (uint32_t count, int32_t bufSize, void *sources, void *types, void *ids, void *severities, void *lengths, void *messageLog)) \
    X(uint32_t, glGetError, (void)) \
    X(void, glGetFixedv, (uint32_t pname, void *params)) \
    X(void, glGetFixedvOES, (uint32_t pname, void *params)) \
    X(void, glGetFloatv, (uint32_t pname, void *data)) \
    X(int32_t, glGetFragDataLocation, (uint32_t program, const void *name)) \
    X(void, glGetFramebufferAttachmentParameteriv, (uint32_t target, uint32_t attachment, uint32_t pname, void *params)) \
    X(void, glGetFramebufferAttachmentParameterivOES, (uint32_t target, uint32_t attachment, uint32_t pname, void *params)) \
    X(void, glGetFramebufferParameteriv, (uint32_t target, uint32_t pname, void *params)) \
    X(uint32_t, glGetGraphicsResetStatus, (void)) \
    X(void, glGetInteger64i_v, (uint32_t target, uint32_t index, void *data)) \
    X(void, glGetInteger64v, (uint32_t pname, void *data)) \
    X(void, glGetIntegeri_v, (uint32_t target, uint32_t index, void *data)) \
    X(void, glGetIntegerv, (uint32_t pname, void *data)) \
    X(void, glGetInternalformativ, (uint32_t target, uint32_t internalformat, uint32_t pname, int32_t count, void *params)) \
    X(void, glGetLightfv, (uint32_t light, uint32_t pname, void *params)) \
    X(void, glGetLightxv, (uint32_t light, uint32_t pname, void *params)) \
    X(void, glGetLightxvOES, (uint32_t light, uint32_t pname, void *params)) \
    X(void, glGetMaterialfv, (uint32_t face, uint32_t pname, void *params)) \
    X(void, glGetMaterialxv, (uint32_t face, uint32_t pname, void *params)) \
    X(void, glGetMaterialxvOES, (uint32_t face, uint32_t pname, void *params)) \
    X(void, glGetMultisamplefv, (uint32_t pname, uint32_t index, void *val)) \
    X(void, glGetObjectLabel, (uint32_t identifier, uint32_t name, int32_t bufSize, void *length, void *label)) \
    X(void, glGetObjectPtrLabel, (const void *ptr, int32_t bufSize, void *length, void *label)) \
    X(void, glGetPointerv, (uint32_t pname, void **params)) \
    X(void, glGetProgramBinary, (uint32_t program, int32_t bufSize, void *length, void *binaryFormat, void *binary)) \
    X(void, glGetProgramInfoLog, (uint32_t program, int32_t bufSize, void *length, void *infoLog)) \
    X(void, glGetProgramInterfaceiv, (uint32_t program, uint32_t programInterface, uint32_t pname, void *params)) \
    X(void, glGetProgramPipelineInfoLog, (uint32_t pipeline, int32_t bufSize, void *length, void *infoLog)) \
    X(void, glGetProgramPipelineiv, (uint32_t pipeline, uint32_t pname, void *params)) \
    X(uint32_t, glGetProgramResourceIndex, (uint32_t program, uint32_t programInterface, const void *name)) \
    X(int32_t, glGetProgramResourceLocation, (uint32_t program, uint32_t programInterface, const void *name)) \
    X(void, glGetProgramResourceName, (uint32_t program, uint32_t programInterface, uint32_t index, int32_t bufSize, void *length, void *name)) \
    X(void, glGetProgramResourceiv, (uint32_t program, uint32_t programInterface, uint32_t index, int32_t propCount, const void *props, int32_t bufSize, void *length, void *params)) \
    X(void, glGetProgramiv, (uint32_t program, uint32_t pname, void *params)) \
    X(void, glGetQueryObjectuiv, (uint32_t id, uint32_t pname, void *params)) \
    X(void, glGetQueryiv, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetRenderbufferParameteriv, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetRenderbufferParameterivOES, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetSamplerParameterIiv, (uint32_t sampler, uint32_t pname, void *params)) \
    X(void, glGetSamplerParameterIivEXT, (uint32_t sampler, uint32_t pname, void *params)) \
    X(void, glGetSamplerParameterIuiv, (uint32_t sampler, uint32_t pname, void *params)) \
    X(void, glGetSamplerParameterIuivEXT, (uint32_t sampler, uint32_t pname, void *params)) \
    X(void, glGetSamplerParameterfv, (uint32_t sampler, uint32_t pname, void *params)) \
    X(void, glGetSamplerParameteriv, (uint32_t sampler, uint32_t pname, void *params)) \
    X(void, glGetShaderInfoLog, (uint32_t shader, int32_t bufSize, void *length, void *infoLog)) \
    X(void, glGetShaderPrecisionFormat, (uint32_t shadertype, uint32_t precisiontype, void *range, void *precision)) \
    X(void, glGetShaderSource, (uint32_t shader, int32_t bufSize, void *length, void *source)) \
    X(void, glGetShaderiv, (uint32_t shader, uint32_t pname, void *params)) \
    X(const void *, glGetString, (uint32_t name)) \
    X(const void *, glGetStringi, (uint32_t name, uint32_t index)) \
    X(void, glGetSynciv, (void *sync, uint32_t pname, int32_t count, void *length, void *values)) \
    X(void, glGetTexEnvfv, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTexEnviv, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTexEnvxv, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTexEnvxvOES, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTexGenfvOES, (uint32_t coord, uint32_t pname, void *params)) \
    X(void, glGetTexGenivOES, (uint32_t coord, uint32_t pname, void *params)) \
    X(void, glGetTexGenxvOES, (uint32_t coord, uint32_t pname, void *params)) \
    X(void, glGetTexLevelParameterfv, (uint32_t target, int32_t level, uint32_t pname, void *params)) \
    X(void, glGetTexLevelParameteriv, (uint32_t target, int32_t level, uint32_t pname, void *params)) \
    X(void, glGetTexParameterIiv, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTexParameterIivEXT, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTexParameterIuiv, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTexParameterIuivEXT, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTexParameterfv, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTexParameteriv, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTexParameterxv, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTexParameterxvOES, (uint32_t target, uint32_t pname, void *params)) \
    X(void, glGetTransformFeedbackVarying, (uint32_t program, uint32_t index, int32_t bufSize, void *length, void *size, void *type, void *name)) \
    X(uint32_t, glGetUniformBlockIndex, (uint32_t program, const void *uniformBlockName)) \
    X(void, glGetUniformIndices, (uint32_t program, int32_t uniformCount, const char *const *uniformNames, void *uniformIndices)) \
    X(int32_t, glGetUniformLocation, (uint32_t program, const void *name)) \
    X(void, glGetUniformfv, (uint32_t program, int32_t location, void *params)) \
    X(void, glGetUniformiv, (uint32_t program, int32_t location, void *params)) \
    X(void, glGetUniformuiv, (uint32_t program, int32_t location, void *params)) \
    X(void, glGetVertexAttribIiv, (uint32_t index, uint32_t pname, void *params)) \
    X(void, glGetVertexAttribIuiv, (uint32_t index, uint32_t pname, void *params)) \
    X(void, glGetVertexAttribfv, (uint32_t index, uint32_t pname, void *params)) \
    X(void, glGetVertexAttribiv, (uint32_t index, uint32_t pname, void *params)) \
    X(void, glGetnUniformfv, (uint32_t program, int32_t location, int32_t bufSize, void *params)) \
    X(void, glGetnUniformiv, (uint32_t program, int32_t location, int32_t bufSize, void *params)) \
    X(void, glGetnUniformuiv, (uint32_t program, int32_t location, int32_t bufSize, void *params)) \
    X(void, glHint, (uint32_t target, uint32_t mode)) \
    X(void, glInvalidateFramebuffer, (uint32_t target, int32_t numAttachments, const void *attachments)) \
    X(void, glInvalidateSubFramebuffer, (uint32_t target, int32_t numAttachments, const void *attachments, int32_t x, int32_t y, int32_t width, int32_t height)) \
    X(uint8_t, glIsBuffer, (uint32_t buffer)) \
    X(uint8_t, glIsEnabled, (uint32_t cap)) \
    X(uint8_t, glIsEnabledi, (uint32_t target, uint32_t index)) \
    X(uint8_t, glIsEnablediEXT, (uint32_t target, uint32_t index)) \
    X(uint8_t, glIsFramebuffer, (uint32_t framebuffer)) \
    X(uint8_t, glIsFramebufferOES, (uint32_t framebuffer)) \
    X(uint8_t, glIsProgram, (uint32_t program)) \
    X(uint8_t, glIsProgramPipeline, (uint32_t pipeline)) \
    X(uint8_t, glIsQuery, (uint32_t id)) \
    X(uint8_t, glIsRenderbuffer, (uint32_t renderbuffer)) \
    X(uint8_t, glIsRenderbufferOES, (uint32_t renderbuffer)) \
    X(uint8_t, glIsSampler, (uint32_t sampler)) \
    X(uint8_t, glIsShader, (uint32_t shader)) \
    X(uint8_t, glIsSync, (void *sync)) \
    X(uint8_t, glIsTexture, (uint32_t texture)) \
    X(uint8_t, glIsTransformFeedback, (uint32_t id)) \
    X(uint8_t, glIsVertexArray, (uint32_t array)) \
    X(void, glLightModelf, (uint32_t pname, float param)) \
    X(void, glLightModelfv, (uint32_t pname, const void *params)) \
    X(void, glLightModelx, (uint32_t pname, int32_t param)) \
    X(void, glLightModelxOES, (uint32_t pname, int32_t param)) \
    X(void, glLightModelxv, (uint32_t pname, const void *param)) \
    X(void, glLightModelxvOES, (uint32_t pname, const void *param)) \
    X(void, glLightf, (uint32_t light, uint32_t pname, float param)) \
    X(void, glLightfv, (uint32_t light, uint32_t pname, const void *params)) \
    X(void, glLightx, (uint32_t light, uint32_t pname, int32_t param)) \
    X(void, glLightxOES, (uint32_t light, uint32_t pname, int32_t param)) \
    X(void, glLightxv, (uint32_t light, uint32_t pname, const void *params)) \
    X(void, glLightxvOES, (uint32_t light, uint32_t pname, const void *params)) \
    X(void, glLineWidth, (float width)) \
    X(void, glLineWidthx, (int32_t width)) \
    X(void, glLineWidthxOES, (int32_t width)) \
    X(void, glLinkProgram, (uint32_t program)) \
    X(void, glLoadIdentity, (void)) \
    X(void, glLoadMatrixf, (const void *m)) \
    X(void, glLoadMatrixx, (const void *m)) \
    X(void, glLoadMatrixxOES, (const void *m)) \
    X(void, glLoadPaletteFromModelViewMatrixOES, (void)) \
    X(void, glLogicOp, (uint32_t opcode)) \
    X(void *, glMapBufferRange, (uint32_t target, intptr_t offset, intptr_t length, uint32_t access)) \
    X(void, glMaterialf, (uint32_t face, uint32_t pname, float param)) \
    X(void, glMaterialfv, (uint32_t face, uint32_t pname, const void *params)) \
    X(void, glMaterialx, (uint32_t face, uint32_t pname, int32_t param)) \
    X(void, glMaterialxOES, (uint32_t face, uint32_t pname, int32_t param)) \
    X(void, glMaterialxv, (uint32_t face, uint32_t pname, const void *param)) \
    X(void, glMaterialxvOES, (uint32_t face, uint32_t pname, const void *param)) \
    X(void, glMatrixIndexPointerOES, (int32_t size, uint32_t type, int32_t stride, const void *pointer)) \
    X(void, glMatrixMode, (uint32_t mode)) \
    X(void, glMemoryBarrier, (uint32_t barriers)) \
    X(void, glMemoryBarrierByRegion, (uint32_t barriers)) \
    X(void, glMinSampleShading, (float value)) \
    X(void, glMinSampleShadingOES, (float value)) \
    X(void, glMultMatrixf, (const void *m)) \
    X(void, glMultMatrixx, (const void *m)) \
    X(void, glMultMatrixxOES, (const void *m)) \
    X(void, glMultiTexCoord4f, (uint32_t target, float s, float t, float r, float q)) \
    X(void, glMultiTexCoord4x, (uint32_t texture, int32_t s, int32_t t, int32_t r, int32_t q)) \
    X(void, glMultiTexCoord4xOES, (uint32_t texture, int32_t s, int32_t t, int32_t r, int32_t q)) \
    X(void, glNormal3f, (float nx, float ny, float nz)) \
    X(void, glNormal3x, (int32_t nx, int32_t ny, int32_t nz)) \
    X(void, glNormal3xOES, (int32_t nx, int32_t ny, int32_t nz)) \
    X(void, glNormalPointer, (uint32_t type, int32_t stride, const void *pointer)) \
    X(void, glObjectLabel, (uint32_t identifier, uint32_t name, int32_t length, const void *label)) \
    X(void, glObjectLabelKHR, (uint32_t identifier, uint32_t name, int32_t length, const void *label)) \
    X(void, glObjectPtrLabel, (const void *ptr, int32_t length, const void *label)) \
    X(void, glOrthof, (float l, float r, float b, float t, float n, float f)) \
    X(void, glOrthofOES, (float l, float r, float b, float t, float n, float f)) \
    X(void, glOrthox, (int32_t l, int32_t r, int32_t b, int32_t t, int32_t n, int32_t f)) \
    X(void, glOrthoxOES, (int32_t l, int32_t r, int32_t b, int32_t t, int32_t n, int32_t f)) \
    X(void, glPatchParameteri, (uint32_t pname, int32_t value)) \
    X(void, glPatchParameteriEXT, (uint32_t pname, int32_t value)) \
    X(void, glPauseTransformFeedback, (void)) \
    X(void, glPixelStorei, (uint32_t pname, int32_t param)) \
    X(void, glPointParameterf, (uint32_t pname, float param)) \
    X(void, glPointParameterfv, (uint32_t pname, const void *params)) \
    X(void, glPointParameterx, (uint32_t pname, int32_t param)) \
    X(void, glPointParameterxOES, (uint32_t pname, int32_t param)) \
    X(void, glPointParameterxv, (uint32_t pname, const void *params)) \
    X(void, glPointParameterxvOES, (uint32_t pname, const void *params)) \
    X(void, glPointSize, (float size)) \
    X(void, glPointSizePointerOES, (uint32_t type, int32_t stride, const void *pointer)) \
    X(void, glPointSizex, (int32_t size)) \
    X(void, glPointSizexOES, (int32_t size)) \
    X(void, glPolygonOffset, (float factor, float units)) \
    X(void, glPolygonOffsetx, (int32_t factor, int32_t units)) \
    X(void, glPolygonOffsetxOES, (int32_t factor, int32_t units)) \
    X(void, glPopDebugGroup, (void)) \
    X(void, glPopDebugGroupKHR, (void)) \
    X(void, glPopMatrix, (void)) \
    X(void, glPrimitiveBoundingBox, (float minX, float minY, float minZ, float minW, float maxX, float maxY, float maxZ, float maxW)) \
    X(void, glPrimitiveBoundingBoxEXT, (float minX, float minY, float minZ, float minW, float maxX, float maxY, float maxZ, float maxW)) \
    X(void, glProgramBinary, (uint32_t program, uint32_t binaryFormat, const void *binary, int32_t length)) \
    X(void, glProgramParameteri, (uint32_t program, uint32_t pname, int32_t value)) \
    X(void, glProgramUniform1f, (uint32_t program, int32_t location, float v0)) \
    X(void, glProgramUniform1fv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniform1i, (uint32_t program, int32_t location, int32_t v0)) \
    X(void, glProgramUniform1iv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniform1ui, (uint32_t program, int32_t location, uint32_t v0)) \
    X(void, glProgramUniform1uiv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniform2f, (uint32_t program, int32_t location, float v0, float v1)) \
    X(void, glProgramUniform2fv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniform2i, (uint32_t program, int32_t location, int32_t v0, int32_t v1)) \
    X(void, glProgramUniform2iv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniform2ui, (uint32_t program, int32_t location, uint32_t v0, uint32_t v1)) \
    X(void, glProgramUniform2uiv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniform3f, (uint32_t program, int32_t location, float v0, float v1, float v2)) \
    X(void, glProgramUniform3fv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniform3i, (uint32_t program, int32_t location, int32_t v0, int32_t v1, int32_t v2)) \
    X(void, glProgramUniform3iv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniform3ui, (uint32_t program, int32_t location, uint32_t v0, uint32_t v1, uint32_t v2)) \
    X(void, glProgramUniform3uiv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniform4f, (uint32_t program, int32_t location, float v0, float v1, float v2, float v3)) \
    X(void, glProgramUniform4fv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniform4i, (uint32_t program, int32_t location, int32_t v0, int32_t v1, int32_t v2, int32_t v3)) \
    X(void, glProgramUniform4iv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniform4ui, (uint32_t program, int32_t location, uint32_t v0, uint32_t v1, uint32_t v2, uint32_t v3)) \
    X(void, glProgramUniform4uiv, (uint32_t program, int32_t location, int32_t count, const void *value)) \
    X(void, glProgramUniformMatrix2fv, (uint32_t program, int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glProgramUniformMatrix2x3fv, (uint32_t program, int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glProgramUniformMatrix2x4fv, (uint32_t program, int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glProgramUniformMatrix3fv, (uint32_t program, int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glProgramUniformMatrix3x2fv, (uint32_t program, int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glProgramUniformMatrix3x4fv, (uint32_t program, int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glProgramUniformMatrix4fv, (uint32_t program, int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glProgramUniformMatrix4x2fv, (uint32_t program, int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glProgramUniformMatrix4x3fv, (uint32_t program, int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glPushDebugGroup, (uint32_t source, uint32_t id, int32_t length, const void *message)) \
    X(void, glPushDebugGroupKHR, (uint32_t source, uint32_t id, int32_t length, const void *message)) \
    X(void, glPushMatrix, (void)) \
    X(uint32_t, glQueryMatrixxOES, (void *mantissa, void *exponent)) \
    X(void, glReadBuffer, (uint32_t src)) \
    X(void, glReadPixels, (int32_t x, int32_t y, int32_t width, int32_t height, uint32_t format, uint32_t type, void *pixels)) \
    X(void, glReadnPixels, (int32_t x, int32_t y, int32_t width, int32_t height, uint32_t format, uint32_t type, int32_t bufSize, void *data)) \
    X(void, glReleaseShaderCompiler, (void)) \
    X(void, glRenderbufferStorage, (uint32_t target, uint32_t internalformat, int32_t width, int32_t height)) \
    X(void, glRenderbufferStorageMultisample, (uint32_t target, int32_t samples, uint32_t internalformat, int32_t width, int32_t height)) \
    X(void, glRenderbufferStorageOES, (uint32_t target, uint32_t internalformat, int32_t width, int32_t height)) \
    X(void, glResumeTransformFeedback, (void)) \
    X(void, glRotatef, (float angle, float x, float y, float z)) \
    X(void, glRotatex, (int32_t angle, int32_t x, int32_t y, int32_t z)) \
    X(void, glRotatexOES, (int32_t angle, int32_t x, int32_t y, int32_t z)) \
    X(void, glSampleCoverage, (float value, uint8_t invert)) \
    X(void, glSampleCoveragex, (int32_t value, uint8_t invert)) \
    X(void, glSampleCoveragexOES, (int32_t value, uint8_t invert)) \
    X(void, glSampleMaski, (uint32_t maskNumber, uint32_t mask)) \
    X(void, glSamplerParameterIiv, (uint32_t sampler, uint32_t pname, const void *param)) \
    X(void, glSamplerParameterIivEXT, (uint32_t sampler, uint32_t pname, const void *param)) \
    X(void, glSamplerParameterIuiv, (uint32_t sampler, uint32_t pname, const void *param)) \
    X(void, glSamplerParameterIuivEXT, (uint32_t sampler, uint32_t pname, const void *param)) \
    X(void, glSamplerParameterf, (uint32_t sampler, uint32_t pname, float param)) \
    X(void, glSamplerParameterfv, (uint32_t sampler, uint32_t pname, const void *param)) \
    X(void, glSamplerParameteri, (uint32_t sampler, uint32_t pname, int32_t param)) \
    X(void, glSamplerParameteriv, (uint32_t sampler, uint32_t pname, const void *param)) \
    X(void, glScalef, (float x, float y, float z)) \
    X(void, glScalex, (int32_t x, int32_t y, int32_t z)) \
    X(void, glScalexOES, (int32_t x, int32_t y, int32_t z)) \
    X(void, glScissor, (int32_t x, int32_t y, int32_t width, int32_t height)) \
    X(void, glShadeModel, (uint32_t mode)) \
    X(void, glShaderBinary, (int32_t count, const void *shaders, uint32_t binaryFormat, const void *binary, int32_t length)) \
    X(void, glShaderSource, (uint32_t shader, int32_t count, const char *const *string, const void *length)) \
    X(void, glStencilFunc, (uint32_t func, int32_t ref, uint32_t mask)) \
    X(void, glStencilFuncSeparate, (uint32_t face, uint32_t func, int32_t ref, uint32_t mask)) \
    X(void, glStencilMask, (uint32_t mask)) \
    X(void, glStencilMaskSeparate, (uint32_t face, uint32_t mask)) \
    X(void, glStencilOp, (uint32_t fail, uint32_t zfail, uint32_t zpass)) \
    X(void, glStencilOpSeparate, (uint32_t face, uint32_t sfail, uint32_t dpfail, uint32_t dppass)) \
    X(void, glTexBuffer, (uint32_t target, uint32_t internalformat, uint32_t buffer)) \
    X(void, glTexBufferEXT, (uint32_t target, uint32_t internalformat, uint32_t buffer)) \
    X(void, glTexBufferRange, (uint32_t target, uint32_t internalformat, uint32_t buffer, intptr_t offset, intptr_t size)) \
    X(void, glTexBufferRangeEXT, (uint32_t target, uint32_t internalformat, uint32_t buffer, intptr_t offset, intptr_t size)) \
    X(void, glTexCoordPointer, (int32_t size, uint32_t type, int32_t stride, const void *pointer)) \
    X(void, glTexEnvf, (uint32_t target, uint32_t pname, float param)) \
    X(void, glTexEnvfv, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexEnvi, (uint32_t target, uint32_t pname, int32_t param)) \
    X(void, glTexEnviv, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexEnvx, (uint32_t target, uint32_t pname, int32_t param)) \
    X(void, glTexEnvxOES, (uint32_t target, uint32_t pname, int32_t param)) \
    X(void, glTexEnvxv, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexEnvxvOES, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexGenfOES, (uint32_t coord, uint32_t pname, float param)) \
    X(void, glTexGenfvOES, (uint32_t coord, uint32_t pname, const void *params)) \
    X(void, glTexGeniOES, (uint32_t coord, uint32_t pname, int32_t param)) \
    X(void, glTexGenivOES, (uint32_t coord, uint32_t pname, const void *params)) \
    X(void, glTexGenxOES, (uint32_t coord, uint32_t pname, int32_t param)) \
    X(void, glTexGenxvOES, (uint32_t coord, uint32_t pname, const void *params)) \
    X(void, glTexImage2D, (uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t border, uint32_t format, uint32_t type, const void *pixels)) \
    X(void, glTexImage3D, (uint32_t target, int32_t level, int32_t internalformat, int32_t width, int32_t height, int32_t depth, int32_t border, uint32_t format, uint32_t type, const void *pixels)) \
    X(void, glTexParameterIiv, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexParameterIivEXT, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexParameterIuiv, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexParameterIuivEXT, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexParameterf, (uint32_t target, uint32_t pname, float param)) \
    X(void, glTexParameterfv, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexParameteri, (uint32_t target, uint32_t pname, int32_t param)) \
    X(void, glTexParameteriv, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexParameterx, (uint32_t target, uint32_t pname, int32_t param)) \
    X(void, glTexParameterxOES, (uint32_t target, uint32_t pname, int32_t param)) \
    X(void, glTexParameterxv, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexParameterxvOES, (uint32_t target, uint32_t pname, const void *params)) \
    X(void, glTexStorage2D, (uint32_t target, int32_t levels, uint32_t internalformat, int32_t width, int32_t height)) \
    X(void, glTexStorage2DMultisample, (uint32_t target, int32_t samples, uint32_t internalformat, int32_t width, int32_t height, uint8_t fixedsamplelocations)) \
    X(void, glTexStorage3D, (uint32_t target, int32_t levels, uint32_t internalformat, int32_t width, int32_t height, int32_t depth)) \
    X(void, glTexStorage3DMultisample, (uint32_t target, int32_t samples, uint32_t internalformat, int32_t width, int32_t height, int32_t depth, uint8_t fixedsamplelocations)) \
    X(void, glTexStorage3DMultisampleOES, (uint32_t target, int32_t samples, uint32_t internalformat, int32_t width, int32_t height, int32_t depth, uint8_t fixedsamplelocations)) \
    X(void, glTexSubImage2D, (uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t width, int32_t height, uint32_t format, uint32_t type, const void *pixels)) \
    X(void, glTexSubImage3D, (uint32_t target, int32_t level, int32_t xoffset, int32_t yoffset, int32_t zoffset, int32_t width, int32_t height, int32_t depth, uint32_t format, uint32_t type, const void *pixels)) \
    X(void, glTransformFeedbackVaryings, (uint32_t program, int32_t count, const char *const *varyings, uint32_t bufferMode)) \
    X(void, glTranslatef, (float x, float y, float z)) \
    X(void, glTranslatex, (int32_t x, int32_t y, int32_t z)) \
    X(void, glTranslatexOES, (int32_t x, int32_t y, int32_t z)) \
    X(void, glUniform1f, (int32_t location, float v0)) \
    X(void, glUniform1fv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniform1i, (int32_t location, int32_t v0)) \
    X(void, glUniform1iv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniform1ui, (int32_t location, uint32_t v0)) \
    X(void, glUniform1uiv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniform2f, (int32_t location, float v0, float v1)) \
    X(void, glUniform2fv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniform2i, (int32_t location, int32_t v0, int32_t v1)) \
    X(void, glUniform2iv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniform2ui, (int32_t location, uint32_t v0, uint32_t v1)) \
    X(void, glUniform2uiv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniform3f, (int32_t location, float v0, float v1, float v2)) \
    X(void, glUniform3fv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniform3i, (int32_t location, int32_t v0, int32_t v1, int32_t v2)) \
    X(void, glUniform3iv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniform3ui, (int32_t location, uint32_t v0, uint32_t v1, uint32_t v2)) \
    X(void, glUniform3uiv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniform4f, (int32_t location, float v0, float v1, float v2, float v3)) \
    X(void, glUniform4fv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniform4i, (int32_t location, int32_t v0, int32_t v1, int32_t v2, int32_t v3)) \
    X(void, glUniform4iv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniform4ui, (int32_t location, uint32_t v0, uint32_t v1, uint32_t v2, uint32_t v3)) \
    X(void, glUniform4uiv, (int32_t location, int32_t count, const void *value)) \
    X(void, glUniformBlockBinding, (uint32_t program, uint32_t uniformBlockIndex, uint32_t uniformBlockBinding)) \
    X(void, glUniformMatrix2fv, (int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glUniformMatrix2x3fv, (int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glUniformMatrix2x4fv, (int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glUniformMatrix3fv, (int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glUniformMatrix3x2fv, (int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glUniformMatrix3x4fv, (int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glUniformMatrix4fv, (int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glUniformMatrix4x2fv, (int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(void, glUniformMatrix4x3fv, (int32_t location, int32_t count, uint8_t transpose, const void *value)) \
    X(uint8_t, glUnmapBuffer, (uint32_t target)) \
    X(void, glUseProgram, (uint32_t program)) \
    X(void, glUseProgramStages, (uint32_t pipeline, uint32_t stages, uint32_t program)) \
    X(void, glValidateProgram, (uint32_t program)) \
    X(void, glValidateProgramPipeline, (uint32_t pipeline)) \
    X(void, glVertexAttrib1f, (uint32_t index, float x)) \
    X(void, glVertexAttrib1fv, (uint32_t index, const void *v)) \
    X(void, glVertexAttrib2f, (uint32_t index, float x, float y)) \
    X(void, glVertexAttrib2fv, (uint32_t index, const void *v)) \
    X(void, glVertexAttrib3f, (uint32_t index, float x, float y, float z)) \
    X(void, glVertexAttrib3fv, (uint32_t index, const void *v)) \
    X(void, glVertexAttrib4f, (uint32_t index, float x, float y, float z, float w)) \
    X(void, glVertexAttrib4fv, (uint32_t index, const void *v)) \
    X(void, glVertexAttribBinding, (uint32_t attribindex, uint32_t bindingindex)) \
    X(void, glVertexAttribDivisor, (uint32_t index, uint32_t divisor)) \
    X(void, glVertexAttribFormat, (uint32_t attribindex, int32_t size, uint32_t type, uint8_t normalized, uint32_t relativeoffset)) \
    X(void, glVertexAttribI4i, (uint32_t index, int32_t x, int32_t y, int32_t z, int32_t w)) \
    X(void, glVertexAttribI4iv, (uint32_t index, const void *v)) \
    X(void, glVertexAttribI4ui, (uint32_t index, uint32_t x, uint32_t y, uint32_t z, uint32_t w)) \
    X(void, glVertexAttribI4uiv, (uint32_t index, const void *v)) \
    X(void, glVertexAttribIFormat, (uint32_t attribindex, int32_t size, uint32_t type, uint32_t relativeoffset)) \
    X(void, glVertexAttribIPointer, (uint32_t index, int32_t size, uint32_t type, int32_t stride, const void *pointer)) \
    X(void, glVertexAttribPointer, (uint32_t index, int32_t size, uint32_t type, uint8_t normalized, int32_t stride, const void *pointer)) \
    X(void, glVertexBindingDivisor, (uint32_t bindingindex, uint32_t divisor)) \
    X(void, glVertexPointer, (int32_t size, uint32_t type, int32_t stride, const void *pointer)) \
    X(void, glViewport, (int32_t x, int32_t y, int32_t width, int32_t height)) \
    X(void, glWaitSync, (void *sync, uint32_t flags, uint64_t timeout)) \
    X(void, glWeightPointerOES, (int32_t size, uint32_t type, int32_t stride, const void *pointer)) \
    /* end */
